language: ruby

sudo: false

rvm:
  - "2.0.0"
  - "2.1"
  - "2.2"
  - "2.3.0"
  - "2.4.0"
  - "jruby-9.1.5.0"
  - "jruby-head"

script:
  bundle exec rake test

before_install:
  # install latest rubygems
  - gem update --system
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler

dist: trusty

# speed up jruby installation
# https://github.com/travis-ci/docs-travis-ci-com/pull/743
addons:
  apt:
    packages:
      - haveged
